images_path: "./dataset/images/" #Path to the training set
coco_annotations_path: "./annotations/COCO/" #Path to the COCO annotations
#pretrained_model: "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml" #downloaded from model_zoo - use this for Faster R-CNN
pretrained_model: "COCO-Detection/retinanet_R_50_FPN_3x.yaml" #downloaded from model_zoo - use this for Retina Net

epochs: 300 #Num epochs
imgsz: 640 #Image size (longest edge)
batch : 8    #default is 4
patience: 20 #default is 20 - used for early stopping
fliplr: 0.5  #default is 0.5
flipud: 0.5  #default is 0.5

#roi_heads: 512 (default is 512, is used by faster RCNN)

#Only output format supported is Pytorch (.pt)


