images_path: "./dataset/images/"
coco_annotations_path: "./annotations/COCO/"
#pretrained_model: "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml" #downloaded from model_zoo
pretrained_model: "COCO-Detection/retinanet_R_50_FPN_3x.yaml"

epochs: 300
imgsz: 160
batch : 8    #default is 4
patience: 10 #default is 20
fliplr: 0.5  #default is 0.5
flipud: 0.5  #default is 0.5

#roi_heads: 512 (default is 512, is used by faster RCNN)

#Only output format supported is Pytorch (.pt)


