
k_folds: 5  #If 1 or less, no k-fold
validation: True 
train_val_test_split: [0.6, 0.1, 0.3] #If k-fold is active this is not used
vgg_annotations_path: "./annotations/VIA/"
annotation_files: [ #Use empty list if you want to consider all json files in the folder
    "Artelab Extended.json",
    "Artelab.json",
    "Bodnar.json",
    "Deal Kaist.json",
    "Dubska.json",
    "InventBar.json",
    "Muenster.json",
    "Open Food Facts.json",
    "ParcelBar.json",
    "SKUU DSP Lab.json",
    "Szentandrasi-Dubska QR.json",
    "ZVZ-real.json"
]
output_path: "./annotations/COCO/"
images_path: "./dataset/images/"
salt: ""
