coco_annotations_path: ./annotations/COCO/
longest_edge_resize: 480
algorithms:
- args:
    lib_path: ./build/Gallo2011-Soros2013-Yun2017/libBarcodeLocalization.so
    winsize: 20
  class: Yun_detector
  library: yun_detector
  name: Yun
- args:
    lib_path: ./build/Zamberletti2013/libBarcodeLibrary.so
    net_path: ./Zamberletti2013/net61x3.net
    winsize: 20
  class: Zamberletti_detector
  library: zamberletti_detector
  name: Zamberletti
- args:
    imgsz: 480
    model_path: ./Saved Models/yolon_480_0.pt
  class: YOLO_detector
  library: ultralytics_detector
  name: Yolo Nano
- args:
    imgsz: 480
    model_path: ./Saved Models/yolom_480_0.pt
  class: YOLO_detector
  library: ultralytics_detector
  name: Yolo Medium
- args:
    imgsz: 480
    model_path: ./Saved Models/rtdetr_480_0.pt
  class: RTDETR_detector
  library: ultralytics_detector
  name: RTDETR Large
- args:
    model_path: ./Saved Models/fasterRCNN_480_0.pt
  class: Detectron2_detector
  library: detectron2_detector
  name: FASTER RCNN
- args:
    model_path: ./Saved Models/retinaNET_480_0.pt
  class: Detectron2_detector
  library: detectron2_detector
  name: RetinaNet
