coco_annotations_path: ./annotations/COCO/
longest_edge_resize: 320
algorithms:
- args:
    model_path: ./Saved Models/zharkov_320_4.pt
  class: Zharkov_detector
  library: zharkov_detector
  name: Zharkov
- args:
    imgsz: 320
    model_path: ./Saved Models/yolon_320_4.pt
  class: YOLO_detector
  library: ultralytics_detector
  name: Yolo Nano
- args:
    imgsz: 320
    model_path: ./Saved Models/yolom_320_4.pt
  class: YOLO_detector
  library: ultralytics_detector
  name: Yolo Medium
- args:
    imgsz: 320
    model_path: ./Saved Models/rtdetr_320_4.pt
  class: RTDETR_detector
  library: ultralytics_detector
  name: RTDETR Large
- args:
    model_path: ./Saved Models/fasterRCNN_320_4.pt
  class: Detectron2_detector
  library: detectron2_detector
  name: FASTER RCNN
- args:
    model_path: ./Saved Models/retinaNET_320_4.pt
  class: Detectron2_detector
  library: detectron2_detector
  name: RetinaNet
