coco_annotations_path: ./annotations/COCO/
longest_edge_resize: 640
class: 2D
single_ROI: true
bins: [-100, 0, 0.5,1.0,1.5,2.0,2.5,3.0,3.5,4.0,100]
algorithms:
- args:
    lib_path: ./build/Gallo2011-Soros2013-Yun2017/libBarcodeLocalization.so
    winsize: 30
    detectionType: 2D
  class: Soros_detector
  library: soros_detector
  name: Soros30
- args:
    lib_path: ./build/Gallo2011-Soros2013-Yun2017/libBarcodeLocalization.so
    winsize: 35
    detectionType: 2D
  class: Soros_detector
  library: soros_detector
  name: Soros35
- args:
    lib_path: ./build/Gallo2011-Soros2013-Yun2017/libBarcodeLocalization.so
    winsize: 40
    detectionType: 2D
  class: Soros_detector
  library: soros_detector
  name: Soros40
- args:
    model_path: ./Saved Models/zharkov_640_4.pt
  class: Zharkov_detector
  library: zharkov_detector
  name: Zharkov
- args:
    imgsz: 640
    model_path: ./Saved Models/yolon_640_4.pt
  class: YOLO_detector
  library: ultralytics_detector
  name: Yolo Nano
- args:
    imgsz: 640
    model_path: ./Saved Models/yolom_640_4.pt
  class: YOLO_detector
  library: ultralytics_detector
  name: Yolo Medium
- args:
    imgsz: 640
    model_path: ./Saved Models/rtdetr_640_4.pt
  class: RTDETR_detector
  library: ultralytics_detector
  name: RTDETR Large
- args:
    model_path: ./Saved Models/fasterRCNN_640_4.pt
  class: Detectron2_detector
  library: detectron2_detector
  name: FASTER RCNN
- args:
    model_path: ./Saved Models/retinaNET_640_4.pt
  class: Detectron2_detector
  library: detectron2_detector
  name: RetinaNet
