coco_annotations_path: ./annotations/COCO/
longest_edge_resize: 320
class: 1D
single_ROI: true
bins:
- -100
- 0
- 0.5
- 1.0
- 1.5
- 2.0
- 2.5
- 3.0
- 3.5
- 4.0
- 100
algorithms:
#- args:
#    imgsz: 640
#    model_path: ./Saved Models/yolon_640_0.pt
#  class: YOLO_detector
#  library: ultralytics_detector
#  name: Yolo Nano
#- args:
#    imgsz: 640
#    model_path: ./Saved Models/yolom_640_0.pt
#  class: YOLO_detector
#  library: ultralytics_detector
#  name: Yolo Medium
#- args:
#    imgsz: 640
#    model_path: ./Saved Models/rtdetr_640_0.pt
#  class: RTDETR_detector
#  library: ultralytics_detector
#  name: RTDETR Large
#- args:
#    model_path: ./Saved Models/fasterRCNN_640_0.pt
#  class: Detectron2_detector
#  library: detectron2_detector
#  name: FASTER RCNN
#- args:
#    model_path: ./Saved Models/retinaNET_640_0.pt
#  class: Detectron2_detector
#  library: detectron2_detector
#  name: RetinaNet

- args:
    model_path: ./Saved Models/fasterSeg_xl_320_0.pt
    minArea: 200
    activation: softmax
    gray_scale: false
    remove_first_channel: true
  class: Pytorch_segmenter
  library: pytorch_segmentation
  name: FasterSeg XL

- args:
    model_path: ./Saved Models/fscnn_nano_320_0.pt
    minArea: 200
    activation: sigmoid
    gray_scale: true
    remove_first_channel: false
  class: Pytorch_segmenter
  library: pytorch_segmentation
  name: FSCNN Nano
#- args:
#    model_path: ./Saved Models/zharkov_640_0.pt
#  class: Zharkov_detector
#  library: zharkov_detector
#  name: Zharkov
- args:
    lib_path: ./build/Gallo2011-Soros2013-Yun2017/libBarcodeLocalization.so
    winsize: 15
  class: Gallo_detector
  library: gallo_detector
  name: Gallo15
- args:
    lib_path: ./build/Gallo2011-Soros2013-Yun2017/libBarcodeLocalization.so
    winsize: 15
  class: Soros_detector
  library: soros_detector
  name: Soros15
- args:
    lib_path: ./build/Gallo2011-Soros2013-Yun2017/libBarcodeLocalization.so
    winsize: 30
  class: Yun_detector
  library: yun_detector
  name: Yun30
- args:
    lib_path: ./build/Zamberletti2013/libBarcodeLibrary.so
    net_path: ./Zamberletti2013/net61x3.net
  class: Zamberletti_detector
  library: zamberletti_detector
  name: Zamberletti
