coco_annotations_path: ./annotations/COCO/
longest_edge_resize: 320
algorithms:
- args:
    imgsz: 320
    model_path: ./Saved Models/yolon_320_4.pt
  class: YOLO_detector
  library: ultralytics_detector
  name: Yolo Nano
- args:
    model_path: ./Saved Models/bafalo_scnn_192-448_4.pt
    minArea: 300
    th: 0.4
    activation: sigmoid
    gray_scale: false
    remove_first_channel: false
  class: Pytorch_segmenter
  library: pytorch_segmentation
  name: BaFalo SCNN
- args:
    model_path: ./Saved Models/bafalo_scnn_noshuffle_192-448_4.pt
    minArea: 300
    th: 0.4
    activation: sigmoid
    gray_scale: false
    remove_first_channel: false
  class: Pytorch_segmenter
  library: pytorch_segmentation
  name: BaFalo SCNN noshuffle
- args:
    model_path: ./Saved Models/bisenet_0.25x_192-448_4.pt
    minArea: 300
    th: 0.4
    activation: sigmoid
    gray_scale: false
    remove_first_channel: false
  class: Pytorch_segmenter
  library: pytorch_segmentation
  name: Bisenet 0.25x
- args:
    model_path: ./Saved Models/contextnet_0.25x_192-448_4.pt
    minArea: 300
    th: 0.4
    activation: sigmoid
    gray_scale: false
    remove_first_channel: false
  class: Pytorch_segmenter
  library: pytorch_segmentation
  name: ContextNet 0.25x
- args:
    model_path: ./Saved Models/fscnn_0.25x_192-448_4.pt
    minArea: 300
    th: 0.4
    activation: sigmoid
    gray_scale: false
    remove_first_channel: false
  class: Pytorch_segmenter
  library: pytorch_segmentation
  name: FSCNN 0.25x
- args:
    model_path: ./Saved Models/fscnn_0.5x_192-448_4.pt
    minArea: 300
    th: 0.4
    activation: sigmoid
    gray_scale: false
    remove_first_channel: false
  class: Pytorch_segmenter
  library: pytorch_segmentation
  name: FSCNN 0.5x
- args:
    model_path: ./Saved Models/zharkov_320_4.pt
  class: Zharkov_detector
  library: zharkov_detector
  name: Zharkov
