coco_annotations_path: ./annotations/COCO/
define: &img_size 320
longest_edge_resize: *img_size
num_repeats: 3
num_threads: 1
step: 4
define: &device 'cpu'

algorithms:
- args:
    model_path: ./Saved Models/zharkov_640_4.pt
  class: Zharkov_detector
  library: zharkov_detector
  name: Zharkov
  device: *device
- args:
    model_path: ./Saved Models/fasterRCNN_640_4.pt
    device: *device
  class: Detectron2_detector
  library: detectron2_detector
  name: FASTER RCNN
- args:
    imgsz: *img_size
    model_path: ./Saved Models/yolon_640_4.pt
    device: *device
  class: YOLO_detector
  library: ultralytics_detector
  name: Yolo Nano
- args:
    imgsz: *img_size
    model_path: ./Saved Models/yolopico_ghost_640_0.pt
    device: *device
  class: YOLO_detector
  library: ultralytics_detector
  name: Yolo Pico Ghost
- args:
    imgsz: *img_size
    model_path: ./Saved Models/yolom_640_4.pt
    device: *device
  class: YOLO_detector
  library: ultralytics_detector
  name: Yolo Medium
- args:
    imgsz: *img_size
    model_path: ./Saved Models/rtdetr_640_4.pt
    device: *device
  class: RTDETR_detector
  library: ultralytics_detector
  name: RTDETR Large
- args:
    model_path: ./Saved Models/retinaNET_640_4.pt
    device: *device
  class: Detectron2_detector
  library: detectron2_detector
  name: RetinaNet
- args:
    lib_path: ./build/Gallo2011-Soros2013-Yun2017/libBarcodeLocalization.so
    winsize: 15
  class: Gallo_detector
  library: gallo_detector
  name: Gallo15
- args:
    lib_path: ./build/Gallo2011-Soros2013-Yun2017/libBarcodeLocalization.so
    winsize: 15
  class: Soros_detector
  library: soros_detector
  name: Soros15
- args:
    lib_path: ./build/Gallo2011-Soros2013-Yun2017/libBarcodeLocalization.so
    winsize: 30
  class: Yun_detector
  library: yun_detector
  name: Yun30
- args:
    lib_path: ./build/Zamberletti2013/libBarcodeLibrary.so
    net_path: ./Zamberletti2013/net61x3.net
  class: Zamberletti_detector
  library: zamberletti_detector
  name: Zamberletti
